"""add_supabase_appwrite_integrations

Revision ID: 37ff0751c998
Revises: a1b2c3d4e5f6
Create Date: 2026-02-28 00:51:32.195545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.migration_helpers import uuid_server_default, now_server_default
from app.db.types import EncryptedString

# revision identifiers, used by Alembic.
revision: str = '37ff0751c998'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=now_server_default(), nullable=False))
    op.add_column('otp_codes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=now_server_default(), nullable=False))
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.add_column('user_settings', sa.Column('supabase_url', sa.String(length=512), nullable=True))
    op.add_column('user_settings', sa.Column('supabase_anon_key', EncryptedString(), nullable=True))
    op.add_column('user_settings', sa.Column('supabase_service_role_key', EncryptedString(), nullable=True))
    op.add_column('user_settings', sa.Column('supabase_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('appwrite_endpoint', sa.String(length=512), nullable=True))
    op.add_column('user_settings', sa.Column('appwrite_project_id', sa.String(length=128), nullable=True))
    op.add_column('user_settings', sa.Column('appwrite_api_key', EncryptedString(), nullable=True))
    op.add_column('user_settings', sa.Column('appwrite_connected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'appwrite_connected_at')
    op.drop_column('user_settings', 'appwrite_api_key')
    op.drop_column('user_settings', 'appwrite_project_id')
    op.drop_column('user_settings', 'appwrite_endpoint')
    op.drop_column('user_settings', 'supabase_connected_at')
    op.drop_column('user_settings', 'supabase_service_role_key')
    op.drop_column('user_settings', 'supabase_anon_key')
    op.drop_column('user_settings', 'supabase_url')
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.drop_column('otp_codes', 'updated_at')
    op.drop_column('otp_codes', 'created_at')
    # ### end Alembic commands ###
