"""add_enterprise_mode

Revision ID: 5435ef135f8e
Revises: 777775eab522
Create Date: 2026-02-28 13:17:57.337698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5435ef135f8e'
down_revision: Union[str, None] = '777775eab522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('enterprise_mode', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'enterprise_mode')
    # ### end Alembic commands ###
