"""add_customer_dashboard_tables

Revision ID: 777775eab522
Revises: aa4f5c32c5d5
Create Date: 2026-02-28 12:40:20.443888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.migration_helpers import uuid_server_default, now_server_default
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = '777775eab522'
down_revision: Union[str, None] = 'aa4f5c32c5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', GUID(), server_default=uuid_server_default(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('account_holder', sa.String(length=128), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('routing_number', sa.String(length=32), nullable=True),
    sa.Column('swift_bic', sa.String(length=11), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_notifications',
    sa.Column('id', GUID(), server_default=uuid_server_default(), nullable=False),
    sa.Column('customer_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('invoice_id', GUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('sender_name', sa.String(length=128), nullable=True),
    sa.Column('sender_bank', sa.String(length=128), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('receipt_file_url', sa.String(length=512), nullable=True),
    sa.Column('receipt_file_name', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ticket_id', GUID(), nullable=True),
    sa.Column('verified_by', GUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_requests',
    sa.Column('id', GUID(), server_default=uuid_server_default(), nullable=False),
    sa.Column('customer_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=64), nullable=True),
    sa.Column('desired_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desired_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=512), nullable=True),
    sa.Column('attachment_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ticket_id', GUID(), nullable=True),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('reviewed_by', GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_requests')
    op.drop_table('payment_notifications')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
