"""add_system_settings_table

Revision ID: df9ec17bd091
Revises: 01b9f7f33c2b
Create Date: 2026-02-28 09:12:22.473835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9ec17bd091'
down_revision: Union[str, None] = '01b9f7f33c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'system_settings',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('app_version', sa.String(length=16), nullable=True),
        sa.Column('master_password_hash', sa.String(length=128), nullable=True),
        sa.Column('remote_db_url', sa.Text(), nullable=True),
        sa.Column('remote_db_enabled', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('instance_name', sa.String(length=64), nullable=True),
        sa.Column('is_web_master', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('allow_remote_connections', sa.Boolean(), server_default='false', nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
