"""add_app_version_to_system_settings

Revision ID: fcb463a71cbe
Revises: df9ec17bd091
Create Date: 2026-02-28 09:38:49.047807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb463a71cbe'
down_revision: Union[str, None] = 'df9ec17bd091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
